openapi: 3.0.0
info:
  title: Final Exam Preparation API
  version: 1.0.0
servers:
  - url: http://localhost:3000
components:
  schemas:
    Restaurant:
      type: object
      properties:
        _id:
          type: string
          example: 64b8f0c2e1b2c3d4e5f67890
        name:
          type: string
          example: Pizza Palace
        address:
          type: string
          example: 123 Main St, Toronto
        phoneNumber:
          type: string
          example: 416-123-4567
        emailAddress:
          type: string
          example: info@pizzapalace.com
        rating:
          type: number
          minimum: 1
          maximum: 10
          example: 8
    RestaurantInput:
      type: object
      properties:
        name:
          type: string
          example: Pizza Palace
        address:
          type: string
          example: 123 Main St, Toronto
        phoneNumber:
          type: string
          example: 416-123-4567
        emailAddress:
          type: string
          example: info@pizzapalace.com
        rating:
          type: number
